from __future__ import annotations

from typing import Dict, List, Set

APP_NAME = "Skillora"
APP_TAGLINE = "Where Skills Meet Opportunity"
APP_SUBTITLE = (
    "Upload your resume and compare it against a target job description "
    "to uncover alignment, identify missing skills, and assess fit with clarity."
)

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
SKILL_NER_MODEL_NAME = "Nucha/Nucha_SkillNER_BERT"
REQUEST_TIMEOUT = 12

# Hidden internal thresholds. These are intentionally not shown in the UI.
STRONG_MATCH_THRESHOLD = 0.66
GOOD_MATCH_THRESHOLD = 0.50

SKILL_SYNONYMS: Dict[str, str] = {
    "py": "Python",
    "python": "Python",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "react": "React",
    "reactjs": "React",
    "next": "Next.js",
    "nextjs": "Next.js",
    "vue": "Vue.js",
    "angular": "Angular",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "spring": "Spring",
    "sql": "SQL",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "linux": "Linux",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "opencv": "OpenCV",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "tableau": "Tableau",
    "excel": "Excel",
    "llm": "LLMs",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "ci/cd": "CI/CD",
    "ci cd": "CI/CD",
    "rest": "REST APIs",
    "rest api": "REST APIs",
    "restful api": "REST APIs",
    "api": "APIs",
    "agile": "Agile",
    "scrum": "Scrum",
    "jira": "Jira",
    "figma": "Figma",
    "matplotlib": "Matplotlib",
    "statistics": "Statistics",
    "data visualization": "Data Visualization",
    "dashboard development": "Dashboard Development",
    "kpi reporting": "KPI Reporting",
    "business intelligence": "Business Intelligence",
    "forecasting": "Forecasting",
    "a/b testing": "A/B Testing",
    "ab testing": "A/B Testing",
    "bigquery": "BigQuery",
    "cohort analysis": "Cohort Analysis",
    "retention analysis": "Retention Analysis",
    "data cleaning": "Data Cleaning",
}

SKILL_PATTERNS: List[str] = [
    r"\bpython\b", r"\bc\+\+\b", r"\bc#\b", r"\bjavascript\b", r"\btypescript\b",
    r"\bjava\b", r"\breact(?:js)?\b", r"\bnext(?:\.js|js)?\b", r"\bvue\b", r"\bangular\b",
    r"\bnode(?:\.js|js)?\b", r"\bdjango\b", r"\bflask\b", r"\bfastapi\b",
    r"\bspring\b", r"\bsql\b", r"\bpostgres(?:ql)?\b", r"\bmysql\b", r"\bmongodb\b",
    r"\bredis\b", r"\baws\b", r"\bazure\b", r"\bgcp\b", r"\bdocker\b",
    r"\bkubernetes\b|\bk8s\b", r"\bgit\b", r"\blinux\b", r"\btensorflow\b",
    r"\bpytorch\b|\btorch\b", r"\bscikit-learn\b|\bsklearn\b", r"\bpandas\b",
    r"\bnumpy\b", r"\bopencv\b", r"\bpower\s?bi\b", r"\btableau\b", r"\bexcel\b",
    r"\bnlp\b", r"\bcomputer vision\b", r"\bmachine learning\b", r"\bdeep learning\b",
    r"\bci\/?cd\b", r"\brest(?:ful)? api[s]?\b", r"\bapi[s]?\b", r"\bagile\b",
    r"\bscrum\b", r"\bjira\b", r"\bfigma\b", r"\bstatistics\b",
    r"\bdata visualization\b",
    r"\bdashboard development\b",
    r"\bkpi reporting\b",
    r"\bbusiness intelligence\b",
    r"\bforecasting\b",
    r"\ba\/b testing\b|\bab testing\b",
    r"\bbigquery\b",
    r"\bcohort analysis\b",
    r"\bretention analysis\b",
    r"\bdata cleaning\b",
    r"\bmatplotlib\b",
]

REQUIRED_CUES: List[str] = [
    "required",
    "requirements",
    "must have",
    "must-have",
    "experience with",
    "proficient in",
    "proficiency in",
    "strong knowledge of",
    "hands-on",
    "expertise in",
    "familiarity with",
    "should have",
    "need to have",
    "qualification",
    "preferred",
    "nice to have",
    "Tech stack you will touch",
    "bonus",
]

GENERIC_EXCLUDE: Set[str] = {
    "analysis",
    "analytical",
    "preferred",
    "qualification",
    "qualifications",
    "holder",
    "management",
    "improvement",
    "professional",
    "science",
    "engineering",
    "thinking",
    "solving",
    "intelligence",
    "skills",
    "capabilities",
    "experience",
    "requirement",
    "requirements",
    "knowledge",
    "stakeholder",
    "communication",
    "business",
    "commercial",
    "operations",
    "data",
    "reporting",
    "performance",
}

ALLOWED_SHORT_SKILLS: Set[str] = {"c", "r", "sql", "aws", "gcp"}

CANONICAL_SKILLS = sorted(
    set(SKILL_SYNONYMS.values())
    | {
        "Python",
        "SQL",
        "Excel",
        "Power BI",
        "Tableau",
        "Pandas",
        "NumPy",
        "Matplotlib",
        "Statistics",
        "A/B Testing",
        "BigQuery",
        "Forecasting",
        "Cohort Analysis",
        "Retention Analysis",
        "Data Visualization",
        "Dashboard Development",
        "KPI Reporting",
        "Business Intelligence",
        "Data Cleaning",
        "Machine Learning",
    }
)
